/*
Accidentals are as follows:
    -2 == 'bb' (double flat),
    -1 == 'b' (flat),
    0 == (natural),
    1 == '#' (sharp)
    2 == 'x' (double sharp),
    */

// Scales all have 15 notes (2 octaves)
export const majorScales = {
    C: {
        pitches: [
            ['c/4', 0],
            ['d/4', 0],
            ['e/4', 0],
            ['f/4', 0],
            ['g/4', 0],
            ['a/4', 0],
            ['b/4', 0],
            ['c/5', 0],
            ['d/5', 0],
            ['e/5', 0],
            ['f/5', 0],
            ['g/5', 0],
            ['a/5', 0],
            ['b/5', 0],
            ['c/6', 0],
        ],
    },
    'C#': {
        pitches: [
            ['c/4', 1],
            ['d/4', 1],
            ['e/4', 1],
            ['f/4', 1],
            ['g/4', 1],
            ['a/4', 1],
            ['b/4', 1],
            ['c/5', 1],
            ['d/5', 1],
            ['e/5', 1],
            ['f/5', 1],
            ['g/5', 1],
            ['a/5', 1],
            ['b/5', 1],
            ['c/6', 1],
        ],
    },
    Db: {
        pitches: [
            ['d/4', -1],
            ['e/4', -1],
            ['f/4', 0],
            ['g/4', -1],
            ['a/4', -1],
            ['b/4', -1],
            ['c/5', 0],
            ['d/5', -1],
            ['e/5', -1],
            ['f/5', 0],
            ['g/5', -1],
            ['a/5', -1],
            ['b/5', -1],
            ['c/6', 0],
            ['d/6', -1],
        ],
    },
    D: {
        pitches: [
            ['d/4', 0],
            ['e/4', 0],
            ['f/4', 1],
            ['g/4', 0],
            ['a/4', 0],
            ['b/4', 0],
            ['c/5', 1],
            ['d/5', 0],
            ['e/5', 0],
            ['f/5', 1],
            ['g/5', 0],
            ['a/5', 0],
            ['b/5', 0],
            ['c/6', 1],
            ['d/4', 0],
        ],
    },
    'D#': {
        pitches: [
            ['d/4', 1],
            ['e/4', 1],
            ['f/4', 2],
            ['g/4', 1],
            ['a/4', 1],
            ['b/4', 1],
            ['c/5', 2],
            ['d/5', 1],
            ['e/5', 1],
            ['f/5', 2],
            ['g/5', 1],
            ['a/5', 1],
            ['b/5', 1],
            ['c/6', 2],
            ['d/4', 1],
        ],
    },
    Eb: {
        pitches: [
            ['e/4', -1],
            ['f/4', 0],
            ['g/4', 0],
            ['a/4', -1],
            ['b/4', -1],
            ['c/5', 0],
            ['d/5', 0],
            ['e/5', -1],
            ['f/5', 0],
            ['g/5', 0],
            ['a/5', -1],
            ['b/5', -1],
            ['c/6', 0],
            ['d/6', 0],
            ['e/6', -1],
        ],
    },
    E: {
        pitches: [
            ['e/4', 0],
            ['f/4', 1],
            ['g/4', 1],
            ['a/4', 0],
            ['b/4', 0],
            ['c/5', 1],
            ['d/5', 1],
            ['e/5', 0],
            ['f/5', 1],
            ['g/5', 1],
            ['a/5', 0],
            ['b/5', 0],
            ['c/6', 1],
            ['d/6', 1],
            ['e/6', 0],
        ],
    },
    F: {
        pitches: [
            ['f/4', 0],
            ['g/4', 0],
            ['a/4', 0],
            ['b/4', -1],
            ['c/5', 0],
            ['d/5', 0],
            ['e/5', 0],
            ['f/5', 0],
            ['g/5', 0],
            ['a/5', 0],
            ['b/5', -1],
            ['c/6', 0],
            ['d/6', 0],
            ['e/6', 0],
            ['f/6', 0],
        ],
    },
    'F#': {
        pitches: [
            ['f/4', 1],
            ['g/4', 1],
            ['a/4', 1],
            ['b/4', 0],
            ['c/5', 1],
            ['d/5', 1],
            ['e/5', 1],
            ['f/5', 1],
            ['g/5', 1],
            ['a/5', 1],
            ['b/5', 0],
            ['c/6', 1],
            ['d/6', 1],
            ['e/6', 1],
            ['f/6', 1],
        ],
    },
    Gb: {
        pitches: [
            ['g/4', -1],
            ['a/4', -1],
            ['b/4', -1],
            ['c/5', -1],
            ['d/5', -1],
            ['e/5', -1],
            ['f/5', 0],
            ['g/5', -1],
            ['a/5', -1],
            ['b/5', -1],
            ['c/6', -1],
            ['d/6', -1],
            ['e/6', -1],
            ['f/6', 0],
            ['g/6', -1],
        ],
    },
    G: {
        pitches: [
            ['g/4', 0],
            ['a/4', 0],
            ['b/4', 0],
            ['c/5', 0],
            ['d/5', 0],
            ['e/5', 0],
            ['f/5', 1],
            ['g/5', 0],
            ['a/5', 0],
            ['b/5', 0],
            ['c/6', 0],
            ['d/6', 0],
            ['e/6', 0],
            ['f/6', 1],
            ['g/6', 0],
        ],
    },
    'G#': {
        pitches: [
            ['g/4', 1],
            ['a/4', 1],
            ['b/4', 1],
            ['c/5', 1],
            ['d/5', 1],
            ['e/5', 1],
            ['f/5', 2],
            ['g/5', 1],
            ['a/5', 1],
            ['b/5', 1],
            ['c/6', 1],
            ['d/6', 1],
            ['e/6', 1],
            ['f/6', 2],
            ['g/6', 1],
        ],
    },
    Ab: {
        pitches: [
            ['a/4', -1],
            ['b/4', -1],
            ['c/5', 0],
            ['d/5', -1],
            ['e/5', -1],
            ['f/5', 0],
            ['g/5', 0],
            ['a/5', -1],
            ['b/5', -1],
            ['c/6', 0],
            ['d/6', -1],
            ['e/6', -1],
            ['f/6', 0],
            ['g/6', 0],
            ['a/6', -1],
        ],
    },
    A: {
        pitches: [
            ['a/4', 0],
            ['b/4', 0],
            ['c/5', 1],
            ['d/5', 0],
            ['e/5', 0],
            ['f/5', 1],
            ['g/5', 1],
            ['a/5', 0],
            ['b/5', 0],
            ['c/6', 1],
            ['d/6', 0],
            ['e/6', 0],
            ['f/6', 1],
            ['g/6', 1],
            ['a/6', 0],
        ],
    },
    'A#': {
        pitches: [
            ['a/4', 1],
            ['b/4', 1],
            ['c/5', 2],
            ['d/5', 1],
            ['e/5', 2],
            ['f/5', 2],
            ['g/5', 2],
            ['a/5', 1],
            ['b/5', 1],
            ['c/6', 2],
            ['d/6', 1],
            ['e/6', 2],
            ['f/6', 2],
            ['g/6', 2],
            ['a/6', 1],
        ],
    },
    Bb: {
        pitches: [
            ['b/3', -1],
            ['c/4', 0],
            ['d/4', 0],
            ['e/4', -1],
            ['f/4', 0],
            ['g/4', 0],
            ['a/4', 0],
            ['b/4', -1],
            ['c/5', 0],
            ['d/5', 0],
            ['e/5', -1],
            ['f/5', 0],
            ['g/5', 0],
            ['a/5', 0],
            ['b/5', -1],
        ],
    },
    B: {
        pitches: [
            ['b/3', 0],
            ['c/4', 1],
            ['d/4', 1],
            ['e/4', 0],
            ['f/4', 1],
            ['g/4', 1],
            ['a/4', 1],
            ['b/4', 0],
            ['c/5', 1],
            ['d/5', 1],
            ['e/5', 0],
            ['f/5', 1],
            ['g/5', 1],
            ['a/5', 1],
            ['b/5', 0],
        ],
    },
};

// Scale arrays contain a nested list for each scale degree to include in the new scale from the base (major scale)
// where each nested list has the specified scale degree at index 0 and the necessary alteration at index 1.
export const scaleTypes = {
    ionian: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },
    dorian: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    phrygian: {
        scale: [
            [0, 0],
            [1, -1],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    lydian: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 1],
            [4, 0],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },
    mixolydian: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    aeolian: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    locrian: {
        scale: [
            [0, 0],
            [1, -1],
            [2, -1],
            [3, 0],
            [4, -1],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    'locrian#2': {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, -1],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    major: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },
    melodicMinor: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },
    harmonicMinor: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, 0],
            [7, 0],
        ],
    },
    harmonicMajor: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, 0],
            [7, 0],
        ],
    },
    naturalMinor: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    wholeTone: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 1],
            [4, 1],
            [6, -1],
            [7, 0],
        ],
    },
    majorPentatonic: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [4, 0],
            [5, 0],
            [7, 0],
        ],
    },
    minorPentatonic: {
        scale: [
            [0, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [6, -1],
            [7, 0],
        ],
    },

    traditionalBlues: {
        scale: [
            [0, 0],
            [2, -1],
            [3, 0],
            [3, 1],
            [4, 0],
            [6, -1],
            [7, 0],
        ],
    },

    majorBebop: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [4, 1],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },

    dominantBebop: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, -1],
            [6, 0],
            [7, 0],
        ],
    },

    minorBebop: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, -1],
            [6, 0],
            [7, 0],
        ],
    },

    wholeHalfDiminished: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [3, 1],
            [4, 1],
            [5, 0],
            [6, 0],
            [7, 0],
        ],
    },

    halfWholeDiminished: {
        scale: [
            [0, 0],
            [0, 1],
            [1, 1],
            [2, 0],
            [3, 1],
            [4, 0],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    superLocrian: {
        scale: [
            [0, 0],
            [1, -1],
            [2, -1],
            [3, -1],
            [4, -1],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    mode2HarmonicMinor: {
        scale: [
            [0, 0],
            [1, -1],
            [2, -1],
            [3, 0],
            [4, -1],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    mode2HarmonicMajor: {
        scale: [
            [0, 0],
            [1, 0],
            [2, -1],
            [3, 0],
            [4, -1],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    mode5HarmonicMinor: {
        scale: [
            [0, 0],
            [1, -1],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, -1],
            [6, -1],
            [7, 0],
        ],
    },
    mode5HarmonicMajor: {
        scale: [
            [0, 0],
            [1, -1],
            [2, 0],
            [3, 0],
            [4, 0],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
    lydianDominant: {
        scale: [
            [0, 0],
            [1, 0],
            [2, 0],
            [3, 1],
            [4, 0],
            [5, 0],
            [6, -1],
            [7, 0],
        ],
    },
};

// chord quaities each have an id, pitch/accidental alterations, and an array of viable chord scale names.
export const chordQualities = {
    '6/9': {
        id: 0,
        chord: [
            [0, 0],
            [2, 0],
            [4, 0],
            [5, 0],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Major/Ionian',
                programUse: 'major',
            },
        ],
    },
    maj7: {
        id: 1,
        chord: [
            [0, 0],
            [2, 0],
            [4, 0],
            [6, 0],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Major/Ionian',
                programUse: 'major',
            },
        ],
    },
    'maj7:(#11)': {
        id: 2,
        chord: [
            [0, 0],
            [2, 0],
            [3, 1],
            [6, 0],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Lydian',
                programUse: 'lydian',
            },
        ],
    },
    'maj7(b6)': {
        id: 3,
        chord: [
            [0, 0],
            [2, 0],
            [5, -1],
            [6, -1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Harmonic Major',
                programUse: 'hamronicMajor',
            },
        ],
    },
    'min6/9': {
        id: 4,
        chord: [
            [0, 0],
            [2, -1],
            [4, 0],
            [5, 0],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Melodic Minor',
                programUse: 'melodicMinor',
            },
        ],
    },
    'min(maj7)': {
        id: 5,
        chord: [
            [0, 0],
            [2, -1],
            [4, 0],
            [6, 0],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Melodic Minor',
                programUse: 'melodicMinor',
            },
        ],
    },
    min7: {
        id: 6,
        chord: [
            [0, 0],
            [2, -1],
            [4, 0],
            [6, -1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Dorian',
                programUse: 'dorian',
            },
        ],
    },
    7: {
        id: 7,
        chord: [
            [0, 0],
            [2, 0],
            [4, 0],
            [6, -1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Mixolydian',
                programUse: 'mixolydian',
            },
        ],
    },
    '7(#11)': {
        id: 8,
        chord: [
            [0, 0],
            [2, 0],
            [3, 1],
            [6, -1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Lydian Dominant',
                programUse: 'lydianDominant',
            },
        ],
    },
    '7(b5/#5)': {
        id: 9,
        chord: [
            [0, 0],
            [2, 0],
            [3, -1],
            [3, 1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Whole Tone',
                programUse: 'wholeTone',
            },
        ],
    },
    '7(b9/b13)': {
        id: 10,
        chord: [
            [0, 0],
            [2, 0],
            [5, -1],
            [6, 0],
            [8, -1],
        ],
        chordScaleName: [
            {
                userDisplay: '5th Mode Harmonic Minor',
                programUse: 'mode5HarmonicMinor',
            },
        ],
    },
    '13(b9)': {
        id: 11,
        chord: [
            [0, 0],
            [2, 0],
            [5, 0],
            [6, -1],
            [8, -1],
        ],
        chordScaleName: [
            {
                userDisplay: '5th Mode Harmonic Major',
                programUse: 'mode5HarmonicMajor',
            },
        ],
    },
    '7(#9/#5)': {
        id: 12,
        chord: [
            [0, 0],
            [2, 0],
            [4, 1],
            [6, -1],
            [8, 1],
        ],
        chordScaleName: [
            {
                userDisplay: 'Super Locrian',
                programUse: 'superLocrian',
            },
        ],
    },
    '7(b9/#9/b13)': {
        id: 13,
        chord: [
            [0, 0],
            [1, 1],
            [3, -1],
            [6, -1],
            [8, -1],
        ],
        chordScaleName: [
            {
                userDisplay: 'Phrygian',
                programUse: 'phrygian',
            },
        ],
    },
    '7(b9/#11)': {
        id: 14,
        chord: [
            [0, 0],
            [2, 0],
            [3, 1],
            [6, -1],
            [8, -1],
        ],
        chordScaleName: [
            {
                userDisplay: 'Half Whole Diminished',
                programUse: 'halfWholeDiminished',
            },
        ],
    },
    'min7(b5)': {
        id: 15,
        chord: [
            [0, 0],
            [2, -1],
            [4, -1],
            [6, -1],
            [8, -1],
        ],
        chordScaleName: [
            {
                userDisplay: 'Locrian',
                programUse: 'locrian',
            },
            {
                userDisplay: '2nd Mode Harmonic Minor',
                programUse: 'mode2HarmonicMinor',
            },
        ],
    },
    'min9(b5)': {
        id: 16,
        chord: [
            [0, 0],
            [2, -1],
            [4, -1],
            [6, -1],
            [8, 0],
        ],
        chordScaleName: [
            {
                userDisplay: 'Locrian #2',
                programUse: 'locrian#2',
            },
        ],
    },
    dim7: {
        id: 7,
        chord: [
            [0, 0],
            [2, -1],
            [3, 1],
            [5, 0],
        ],
    },
};
